import AppHeader from "@/components/layout/app-header";
import "tw-elements/dist/css/tw-elements.min.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppFooter from "@/components/layout/app-footer";
import AppPeopleSidebar from "@/components/common/app-people-sidebar/app-people-sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AppPeopleSidebar />
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
